### ISSUE TITLE
Please enable Discussions tab on this repo

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ivan-hc/Steam-appimage#22]
So, for now, let me ask here: would it be possible to merge your improvements to Conty? What do you think about that?

For example, from the README:

> patched EAC-Glibc

I do not know what is that - but Conty EAC-Glibc is not patched?

**Comment by ivan-hc** [comment]
> > patched EAC-Glibc
> 
> I do not know what is that - but Conty EAC-Glibc is not patched?

these are third-party patches from Arch User Repository, so they can be good or may be malicious. All depends on how much the volunteers that write these scripts are trustable.

Its better not to infect also Conty itself. Conty uses thefault Steam from official Arch Linux repositories.

Anyway, also if the repository is mine, 80% of work on Steam is by @Samueru-sama , that is a Steam user.

I wrote the scripts and tried solutions to package Steam, but I'm not a steam user. I needed one to improve this, and because of this, I had this issue you opened one year ago without a solution https://github.com/ivan-hc/Steam-appimage/issues/2

This is how a project improves, with cooperation: one suggests an idea (via issue or by opening a repo, as I did with this one) and others decide to cooperate.

This is why Steam AppImage improves and "AM" has not a GUI yet (see https://github.com/ivan-hc/AM/issues/8), it is a question of seriousness and passion on the part of those who join the discussion, keeping them constantly active until a solution is found.

@Samueru-sama is one of those people, and he helped me a lot with "AM" and recently with GIMP, not to mention this repository, which, as I said, is 80% his. I only used some already existing scripts (from Conty) and adapted them to my workflow in build AppImages. Usability and efficiency are another task, and my main cooperator is the number one in this. Sincerelly.

That said, it costs me nothing to open a tab for discussions, even if I don't see the need, given the many "issues" you opened and that we have largely tried to resolve.

Thanks for your interest.

**Comment by ivan-hc** [comment]
https://github.com/ivan-hc/Steam-appimage/discussions

**Comment by vitaly-zdanevich** [comment]
> these are third-party patches from Arch User Repository, so they can be good or may be malicious. All depends on how much the volunteers that write these scripts are trustable.
> 
> Its better not to infect also Conty itself. Conty uses thefault Steam from official Arch Linux repositories.

Is AppImage necessary here? As I understand, all your improvements can be inside the same container? Also its one of the reason why Gentoo gatekeepers against it - single file container inside single file AppImage.

**Comment by ivan-hc** [comment]
> Is AppImage necessary here? As I understand, all your improvements can be inside the same container? Also its one of the reason why Gentoo gatekeepers against it - single file container inside single file AppImage.

my work is all focused on AppImages, there is an additional security layout in build them:
- you can isolate all dotfiles into a .home directory near the AppImage, with the same name of the AppImage (in AM use `am -H steam`)
- you can use Aisap to sandbox them using Bebblewrap, in a more consistent way than Flatpak (in AM use `am --sandbox steam`)

You can't do this with another kind of programs.

**Comment by vitaly-zdanevich** [comment]
Oh, security, ok, thanks.
