### ISSUE TITLE
Runs as a seperate window icon

### ISSUE THREAD

**Issue by contrarybaton60** [ivan-hc/Steam-appimage#47]
When opening steam (either from launcher or if already pinned) it opens separately from the one pinned and doesn't detect the custom window icon (if you used `am --icons steam` or edited the .desktop file)

https://github.com/user-attachments/assets/cfd27dee-a7c2-435a-a8d5-8b2de023cf32

**Comment by ivan-hc** [comment]
I'm not sure why it happens, I use XFCE and I don't have this feature. The behavior seems to be that of an instance of Firefox or other programs opened via some parameter in the .deskto file... I don't remember the name. I used it in webapps. In Firefox I know that the `--class` option is used. I could be on a completely different path.

Regarding the icons, have you seen if the name indicated in the launcher and that of the theme icon match?

PS: I just noticed that the launcher has different entries for different actions. Maybe the underlying problem is there.

**Comment by Samueru-sama** [comment]
I think this is because steam is missing `StartupWMClass` from the .desktop entry, I just made a PR adding it, check back in a while when a new build is made and try again.

**Comment by contrarybaton60** [comment]
works now!
![image](https://github.com/user-attachments/assets/bf474c4e-4c0e-41a0-bbb7-0feee88ff137)

**Comment by ivan-hc** [comment]
Thank you @Samueru-sama

**Comment by contrarybaton60** [comment]
Now all the installed programs I use are AppImages! (with the exception of virt-manager, and web app of Proton Mail I made with https://github.com/linuxmint/webapp-manager)
